### ISSUE TITLE
encrypting hanging

### ISSUE THREAD

**Issue by SquidNeko** [Shell4026/ShellProtector#12] opened 2024-05-06 14:55 UTC
The encrypter seems to just be hanging and taking a long time doing... Something.
All shader is Poiyomi 8.2
I did see the textures turning rainbow static, but then it just begins hanging.
![hanging](https://github.com/Shell4026/ShellProtector/assets/37712045/db4e00db-9802-43be-b4f2-ff99d1164051)
It ended up taking 20 min before going away(Correction. Loading box reappeared when i clicked the encrypted model...) Afterwards when testing, my avatar didnt turn back normal.

**Comment by Shell4026** [comment] 2024-05-07 10:04
Are there any errors in the console?

**Comment by SquidNeko** [comment] 2024-05-07 19:24
![Error](https://github.com/Shell4026/ShellProtector/assets/37712045/0733af6d-b2eb-4a7f-82ef-7033bb7f3e81)
Lots. 1 Red.
I dont know how to solve it.

**Comment by Shell4026** [comment] 2024-05-08 13:54
I think the error is coming from a Material called Slit. Can you remove that for once?

**Comment by SquidNeko** [comment] 2024-05-08 14:53
Okay, that may have been it. It went through now.
Which should i upload?
The _Encrypted new model it created or Model without the _encrypted

**Comment by Shell4026** [comment] 2024-05-09 11:02
If you've successfully tested the original appearance without any issues, upload your avatar with _encrypted.

**Comment by SquidNeko** [comment] 2024-05-09 18:16
So the tester makes the avatar go back to itself again. But in VRChat with the OSC program started, password put in etc. Its not unlocking my textures.

**Comment by Shell4026** [comment] 2024-05-10 13:23
Are you getting your OSC values in-game? Try changing your password to something else, re-encrypting it, and uploading it.

**Comment by Shell4026** [comment] 2024-05-10 13:32
And make sure the animator "fx" name is replaced with the "fx"_encrypted

**Comment by SquidNeko** [comment] 2024-05-12 05:41
Okay, will try. The guide didnt mention anything about the fx_encrypted. Maybe what im missing.

**Comment by Shell4026** [comment] 2024-05-12 12:49
After pressing the Encrypt button, you will have a duplicate of the avatar and a duplicate of the FX, and the FX will automatically be put into the avatar. If it doesn't, there was an error along the way.

**Comment by SquidNeko** [comment] 2024-05-12 14:47
That FX_Encrypted is in and it doesnt work...

**Comment by SquidNeko** [comment] 2024-05-14 15:52
So i tried to exclude all of these Parameters, but it still wont descrypt the texture once in VRChat.
key_weight, pkey, pkey0, pkey1, pkey2, pkey3, pkey4, pkey5, pkey6, pkay7, pkay8, pkey9, pkey10, pkey11, pkey12, pkey13, pkey14, pkey15, pkey16, encrypt_lock, encrypt_Switch0, encrypt_switch1, encrypt_switch2, encrypt_switch3, encrypt_switch4
Am i missing something? Is there a gameobject or something?

**Comment by SquidNeko** [comment] 2024-05-14 20:00
I got it to unlock now in VRChat. However i dont know why the Slit caused Shellprotect to hang.

**Comment by Shell4026** [comment] 2024-05-16 08:26
Sorry for the reply. Can I know the size or information about the texture used for the Slit?

**Comment by SquidNeko** [comment] 2024-05-20 06:45
Sorry for the long delay in reply.
Size is 8K What other information do you want?

**Comment by Shell4026** [comment] 2024-06-29 06:21
I think the 8k might be the problem, is it the same if I reduce it to 4k?

**Comment by SquidNeko** [comment] 2024-06-29 07:34
Lowering didnt seem to do anything.
I scrapped trying on that part though.

**Comment by Shell4026** [comment] 2024-07-12 21:00
Solved. #16

**Closed by Shell4026** 2024-07-12 21:00 UTC
